language: fortran

sudo: required
dist: trusty

addons:
  apt:
    packages: gfortran-6

before_install:
- sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-6 50

script:
  - make